version: '3.8'

version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgresdb

  # redis:
  #   image: redis:latest

  # pgadmin:
  #   image: dpage/pgadmin4

  # minio:
  #   image: minio/minio

  # mlflow:
  #   image: mlflow/mlflow
 
  # nginx:
  #   image: nginx:latest
  