"""adding_other_document_model

Revision ID: 24c3f7d34fe6
Revises: 7cf2884b4275
Create Date: 2024-01-22 21:23:47.172789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c3f7d34fe6'
down_revision: Union[str, None] = '7cf2884b4275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiti_dokumentu_pavyzdziai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document_content', sa.String(), nullable=True),
    sa.Column('processed_document_content', sa.String(), nullable=True),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kiti_dokumentu_pavyzdziai')
    # ### end Alembic commands ###
