"""initial migration

Revision ID: 41c21bd563d0
Revises: 
Create Date: 2024-01-17 09:34:25.553443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c21bd563d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('igaliojimo_dokumentu_pavyzdziai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document_content', sa.String(), nullable=True),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('igaliojimo_dokumentu_pavyzdziai')
    # ### end Alembic commands ###
