"""initial migration

Revision ID: 7cf2884b4275
Revises: 
Create Date: 2024-01-22 20:23:17.712918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf2884b4275'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('igaliojimo_dokumentu_pavyzdziai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document_content', sa.String(), nullable=True),
    sa.Column('processed_document_content', sa.String(), nullable=True),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serviso_katalogas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paslaugos_kodas', sa.String(), nullable=False),
    sa.Column('institucijos_kodas', sa.Integer(), nullable=True),
    sa.Column('institucijos_pavadinimas', sa.String(), nullable=True),
    sa.Column('paslaugos_pavadinimas', sa.String(), nullable=True),
    sa.Column('paslaugos_tipas', sa.String(), nullable=True),
    sa.Column('el_paslauga', sa.String(), nullable=True),
    sa.Column('tik_notarinis', sa.Boolean(), nullable=True),
    sa.Column('prokuratura', sa.Boolean(), nullable=True),
    sa.Column('aktyvumas', sa.Boolean(), nullable=True),
    sa.Column('galioja_nuo', sa.Date(), nullable=True),
    sa.Column('galioja_iki', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'paslaugos_kodas')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serviso_katalogas')
    op.drop_table('igaliojimo_dokumentu_pavyzdziai')
    # ### end Alembic commands ###
