"""add processed_document_content filed in PowerOfAttorneyDocumentSample table

Revision ID: 82e2a91e28be
Revises: a2eea225649b
Create Date: 2024-01-17 22:47:47.697825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e2a91e28be'
down_revision: Union[str, None] = 'a2eea225649b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('igaliojimo_dokumentu_pavyzdziai', sa.Column('processed_document_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('igaliojimo_dokumentu_pavyzdziai', 'processed_document_content')
    # ### end Alembic commands ###
