name: POA_SERVICE BUILD AND DEPLOY (2024/01)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
        make install
    - name: Install Tesseract OCR
      run: |
        chmod +x ./scripts/ocr_engine_provision.sh
        ./scripts/ocr_engine_provision.sh
    - name: Lint with pylint
      run: |
        make lint
    - name: Test wit pytest
      run: |
        make test
    - name: Build
      run: |
        make build
    - name: Deploy
      run: |
        #make deploy
